name: Publish to Docker

on:
  schedule:
    - cron: 0 0 * * 5
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Get current date/time in the usual format
      #   id: version
      #   run: echo "::set-output name=version::$(sh get_release_info.sh version)"
      - name: Extract Version
        id: version
        run: echo "version=$(sh get_release_info.sh version)" |tee -a $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag: ${{ steps.version.outputs.version }}
          tag_exists_error: false
          message: Latest release

      # # Print result using the env variable.
      # -  run: |
      #     echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # # Print result using the action output.
      # - run: |
      #     echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        if: ${{ steps.tag_create.outputs.tag_exists != true }}
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest, ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.version.outputs.version }}
